[build]
  command = "npm run build"
  publish = "dist"

# Desactivamos el procesamiento secundario de Netlify para que respete exactamente el bundle generado por Vite
[build.processing]
  skip_processing = true

# Reescribe las rutas que soliciten /CYCS_Co/... hacia la raíz para que Netlify funcione con base: '/CYCS_Co/'
[[redirects]]
  from = "/CYCS_Co/*"
  to = "/:splat"
  status = 200

# Soporte para rutas en SPA (HTML5 PushState)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https://cdn.jsdelivr.net https://fonts.googleapis.com https://fonts.gstatic.com https://app.chaport.com https://formspree.io; script-src 'self' 'unsafe-inline' https://app.chaport.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com https://unicons.iconscout.com; img-src 'self' data: https:; connect-src 'self' https://app.chaport.com https://formspree.io;"